import csv
import json
import sys
from pathlib import Path

import pandas as pd
from fastapi import APIRouter
from pydantic import BaseModel

# Fix the import path so FastAPI can find ai_model
sys.path.append(str(Path(__file__).resolve().parents[2]))

from ai_model import grap
from ai_model.data import advisor

router = APIRouter()

STATIC_DIR = Path(__file__).resolve().parent.parent / "static"
GRID_PATH = STATIC_DIR / "ahmedabad_1km_grid.geojson"
FORECAST_JSON = Path(__file__).resolve().parents[1] / "forecast_demo.json"
POLLUTION_CSV = (
    Path(__file__).resolve().parents[2] / "ai_model" / "data" / "grid_pollution_demo.csv"
)


def _load_grid_centroids() -> dict[str, tuple[float, float]]:
    grid = json.loads(GRID_PATH.read_text(encoding="utf-8"))
    return {
        feat["properties"]["grid_id"]: (
            feat["properties"]["centroid_lat"],
            feat["properties"]["centroid_lon"],
        )
        for feat in grid["features"]
    }


_GRID_CENTROIDS = _load_grid_centroids()


def _parse_forecast(data: dict) -> tuple[list[dict], pd.Timestamp]:
    """
    Normalizes forecast_demo.json into rows shaped for advisor.detect_events()
    (cell_id, pred_aqi, datetime, lat, lon). The file is regenerated by either
    extract_forecast.py -> {"base_datetime": ..., "snapshots": [{"offset_hours", "values"}, ...]}
    or live_inference.py -> {grid_id: [{"hour", "aqi"}, ...], "_metadata": {...}}
    so both shapes are supported here.
    """
    if "snapshots" in data:
        base_dt = pd.to_datetime(data["base_datetime"])
        points_by_cell: dict[str, list[tuple[int, float]]] = {}
        for snap in data["snapshots"]:
            hour = snap["offset_hours"]
            for gid, aqi in snap["values"].items():
                points_by_cell.setdefault(gid, []).append((hour, aqi))
    else:
        meta = data.get("_metadata", {})
        base_dt = (
            pd.to_datetime(meta["generated_at"])
            if meta.get("generated_at")
            else pd.Timestamp.utcnow()
        )
        points_by_cell = {
            gid: [(p["hour"], p["aqi"]) for p in points]
            for gid, points in data.items()
            if gid != "_metadata"
        }

    rows = []
    for gid, points in points_by_cell.items():
        centroid = _GRID_CENTROIDS.get(gid)
        if centroid is None:
            continue
        lat, lon = centroid
        for hour, aqi in points:
            rows.append(
                {
                    "cell_id": gid,
                    "pred_aqi": aqi,
                    "datetime": base_dt + pd.Timedelta(hours=hour),
                    "lat": lat,
                    "lon": lon,
                }
            )
    return rows, base_dt


def _current_city_aqi() -> float:
    """City-wide mean AQI from the live snapshot (same source as /maps/getPollution)."""
    with POLLUTION_CSV.open("r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    values = [float(r["value"]) for r in rows]
    return sum(values) / len(values) if values else 0.0


def _build_baseline_advisory(aqi: float) -> dict:
    """
    Always-on "current conditions" card — independent of whether any cell
    crosses a GRAP action threshold. Mirrors how consumer air-quality apps
    (e.g. Google Weather) always surface a status + sensitive-group health
    tip, rather than only speaking up once things get severe.
    """
    stage = grap.get_grap_stage(aqi)
    info = grap.stage_to_dict(stage)
    priority = "low" if stage.severity_rank == 0 else (
        "high" if stage.severity_rank >= 2 else "medium"
    )
    return {
        "cell_id": "CITYWIDE",
        "action": info["key_actions"][0]
        if info["key_actions"]
        else "Continue routine monitoring.",
        "grap_stage": info["stage_name"],
        "start_by": "Ongoing",
        "reason": f"City-wide average AQI is {round(aqi)} ({info['category']}).",
        "priority": priority,
        "confidence": 1.0,
        "grap_source": info["source"],
        "citizen_advisory": info["citizen_advisory"],
        "is_baseline": True,
        "stage_color": info["color"],
    }


class GrapSourceModel(BaseModel):
    issuing_authority: str
    document: str
    revision: str
    url: str
    applies_to: str
    this_project: str


class RecommendationModel(BaseModel):
    cell_id: str
    action: str
    grap_stage: str
    start_by: str
    reason: str
    priority: str
    confidence: float
    grap_source: GrapSourceModel | None = None
    citizen_advisory: list[str] | None = None
    is_baseline: bool = False
    stage_color: str | None = None


class AdvisoryResponse(BaseModel):
    advisories: list[RecommendationModel]


@router.get("/getAdvisory", tags=["Maps"], response_model=AdvisoryResponse)
async def get_advisory():
    """
    Returns a always-on city-wide GRAP status card, plus any cell-specific
    AI-generated recommendations triggered by the 72-hour forecast.
    """
    with open(FORECAST_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    rows, base_dt = _parse_forecast(data)
    df = pd.DataFrame(rows)

    # Detect severe pollution events (Very Poor or worse)
    events = advisor.detect_events(df, base_dt, min_cat="Very Poor")

    # Generate cell-specific recommendations (LLM-backed, falls back to
    # deterministic GRAP rules if OPENROUTER_API_KEY is missing/fails)
    recs = advisor.recommend(events)

    baseline = _build_baseline_advisory(_current_city_aqi())

    return {"advisories": [baseline, *recs]}
